// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpML")>]
[<assembly: AssemblyProductAttribute("FSharpML")>]
[<assembly: AssemblyDescriptionAttribute("Library for the FSharp friendly usage of the ML.NET project")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpML"
    let [<Literal>] AssemblyProduct = "FSharpML"
    let [<Literal>] AssemblyDescription = "Library for the FSharp friendly usage of the ML.NET project"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
